version: "3.3"
services:
  app:
    image: jerryzxm/openshift-test:latest
    environment:
      - REDIS_HOST_BAK=localhost
    depends_on:
      - redis
    ports:
      - 80:8080
    user: root
    networks:
      - appnet1
  redis:
    image: redis:latest
    networks:
      - appnet1

networks:
  appnet1:
